# Eksploracyjna analiza danych (EDA)

W niniejszym notatniku przedstawiono eksploracyjną analizę zbioru danych dotyczących sprzedaży w handlu elektronicznym.

Celem tej analizy jest:
- zrozumienie struktury zbioru danych,
- analiza kluczowych wskaźników sprzedaży,
- identyfikacja trendów sprzedaży,
- zbadanie zachowań produktów i klientów.

## Import bibliotek

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

## Załaduj oczyszczony zbiór danych

Załadowanie zbioru danych przygotowanych podczas etapu czyszczenia danych.

In [3]:
df = pd.read_csv("../data/processed/sales_cleaned.csv")

df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,...,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value,revenue,order_month,order_year,order_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,...,campos dos goytacazes,RJ,1.0,credit_card,2.0,72.19,72.19,2017-09,2017,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,...,santa fe do sul,SP,1.0,credit_card,3.0,259.83,259.83,2017-04,2017,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,...,para de minas,MG,1.0,credit_card,5.0,216.87,216.87,2018-01,2018,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,...,atibaia,SP,1.0,credit_card,2.0,25.78,25.78,2018-08,2018,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,...,varzea paulista,SP,1.0,credit_card,3.0,218.04,218.04,2017-02,2017,218.04

## Przegląd zbioru danych

Sprawdzenie rozmiaru zbioru danych, struktury i typu danych.

In [4]:
print("Dataset shape:", df.shape)

df.info()

Dataset shape: (117581, 34)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117581 entries, 0 to 117580
Data columns (total 34 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       117581 non-null  object
 1   order_item_id                  117581 non-null  int64
 2   product_id                     117581 non-null  object
 3   seller_id                      117581 non-null  object
 4   shipping_limit_date            117581 non-null  object
 5   price                          117581 non-null  float64
 6   freight_value                  117581 non-null  float64
 7   customer_id                    117581 non-null  object
 8   order_status                   117581 non-null  object
 9   order_purchase_timestamp       117581 non-null  object
 10  order_approved_at              117566 non-null  object
 11  order_delivered_carrier_date   116336 non-null  object
 12  order_delivered_customer_date  115014 non-null  object
 13  order_estimated_delivery_date  117581 non-null  object
 14  product_category_name          117581 non-null  object
 15  product_name_lenght            115902 non-null  float64
 16  product_description_lenght     115902 non-null  float64
 17  product_photos_qty             115902 non-null  float64
 18  product_weight_g               117581 non-null  float64
 19  product_length_cm              117581 non-null  float64
 20  product_height_cm              117581 non-null  float64
 21  product_width_cm               117581 non-null  float64
 22  customer_unique_id             117581 non-null  object
 23  customer_zip_code_prefix       117581 non-null  int64
 24  customer_city                  117581 non-null  object
 25  customer_state                 117581 non-null  object
 26  payment_sequential             117581 non-null  float64
 27  payment_type                   117581 non-null  object
 28  payment_installments           117581 non-null  float64
 29  payment_value                  117581 non-null  float64
 30  revenue                        117581 non-null  float64
 31  order_month                    117581 non-null  object
 32  order_year                     117581 non-null  int64
 33  order_value                    117581 non-null  float64
dtypes: float64(14), int64(3), object(17)
memory usage: 30.5+ MB

## Podstawowe statystyki opisowe

In [5]:
df.describe()

,order_item_id,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_zip_code_prefix,payment_sequential,payment_installments,payment_value,revenue,order_year,order_value
count,117581.000000,117581.000000,117581.000000,115902.000000,115902.000000,115902.000000,117581.000000,117581.000000,117581.000000,117581.000000,117581.000000,117581.000000,117581.000000,117581.000000,117581.000000,117581.000000,117581.000000
mean,1.195916,120.823605,20.046812,48.767493,786.950182,2.207874,2114.309497,30.257235,16.630306,23.068574,35047.522338,1.093519,2.939548,172.690828,140.870418,2017.538284,215.171616
std,0.697753,184.415806,15.862452,10.035000,653.039008,1.719536,3788.798201,16.190920,13.458952,11.748468,29818.512026,0.726726,2.774296,267.559704,191.557391,0.505060,468.284143
min,1.000000,0.850000,0.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000,1003.000000,1.000000,0.000000,0.000000,6.080000,2016.000000,10.070000
25%,1.000000,39.900000,13.080000,42.000000,347.000000,1.000000,300.000000,18.000000,8.000000,15.000000,11310.000000,1.000000,1.000000,60.900000,55.280000,2017.000000,68.100000
50%,1.000000,74.900000,16.300000,52.000000,601.000000,1.000000,700.000000,25.000000,13.000000,20.000000,24315.000000,1.000000,2.000000,108.260000,92.150000,2018.000000,120.030000
75%,1.000000,134.900000,21.190000,57.000000,985.000000,3.000000,1800.000000,38.000000,20.000000,30.000000,58540.000000,1.000000,4.000000,189.300000,157.790000,2018.000000,211.830000
max,21.000000,6735.000000,409.680000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000,99990.000000,29.000000,24.000000,13664.080000,6929.310000,2018.000000,13664.080000

## KPI sprzedażowe
Obliczenie podstawowych wskaźników sprzedaży